# Generated by Django 5.0.7 on 2024-08-31 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('active_image', models.ImageField(upload_to='offer')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Clutch bag', 'Clutch bag'), ('Potlis', 'Potlis'), ('Batua bag', 'Batua bag'), ('Bridal bag', 'Bridal bag')], default='Clutch bag', max_length=50)),
                ('collection', models.CharField(choices=[('italian', 'italian collection'), ('indian', 'indian collection'), ('western', 'western collection')], default='indian', max_length=50)),
                ('isExclusive', models.BooleanField(default=False)),
                ('isBestSeller', models.BooleanField(default=False)),
                ('outer_material', models.CharField(max_length=50)),
                ('inner_material', models.CharField(max_length=50)),
                ('sling', models.BooleanField(default=False)),
                ('closer', models.CharField(max_length=50)),
                ('pocket', models.BooleanField(max_length=50)),
            ],
            options={
                'verbose_name': 'Product Cluster',
            },
        ),
        migrations.CreateModel(
            name='OfferImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_name', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='offer')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.offer')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='product',
            field=models.ManyToManyField(related_name='offer_products', to='product.productcluster'),
        ),
        migrations.CreateModel(
            name='SingleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField(max_length=500)),
                ('previous_price', models.PositiveIntegerField(blank=True, null=True)),
                ('length', models.FloatField()),
                ('breath', models.FloatField()),
                ('height', models.FloatField()),
                ('color', models.CharField(max_length=10)),
                ('in_stock', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.productcluster')),
            ],
            options={
                'verbose_name': 'Single Product',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('alt_text', models.CharField(blank=True, max_length=100)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.singleproduct')),
            ],
        ),
    ]
