# Generated by Django 5.0.7 on 2024-07-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleproduct',
            name='previous_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
