# Generated by Django 5.0.7 on 2024-09-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerimage',
            name='alt_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='productcluster',
            name='category',
            field=models.CharField(choices=[('Clutch', 'Clutch Bag'), ('Potli', 'Potli Bag'), ('Batua', 'Batua Bag'), ('Bridal', 'Bridal Bag')], default='Clutch bag', max_length=50),
        ),
        migrations.AlterField(
            model_name='productcluster',
            name='collection',
            field=models.CharField(choices=[('italian', 'Italian Collection'), ('indian', 'Indian Collection'), ('western', 'Western Collection')], default='indian', max_length=50),
        ),
    ]
