# Generated by Django 5.0.7 on 2024-08-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='singleproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
