# Generated by Django 5.0.7 on 2024-07-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_singleproduct_previous_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcluster',
            name='category',
            field=models.CharField(choices=[('Clutch bag', 'Clutch bag'), ('Potlis', 'Potlis'), ('Batua bag', 'Batua bag'), ('Bridal bag', 'Bridal bag')], default='Clutch bag', max_length=50),
        ),
    ]
