# Generated by Django 5.0.7 on 2024-08-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_singleproduct_created_at_singleproduct_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcluster',
            options={'verbose_name': 'Product Cluster'},
        ),
        migrations.AddField(
            model_name='productcluster',
            name='collection',
            field=models.CharField(choices=[('italian', 'italian collection'), ('indian', 'indian collection'), ('western', 'western collection')], default='indian', max_length=50),
        ),
        migrations.AddField(
            model_name='productcluster',
            name='isExclusive',
            field=models.BooleanField(default=False),
        ),
    ]
