# Generated by Django 5.0.7 on 2024-08-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productcluster_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcluster',
            name='isBestSeller',
            field=models.BooleanField(default=False),
        ),
    ]
