# Generated by Django 5.0.7 on 2024-09-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='billing_address_name',
            field=models.CharField(default='N.A.', max_length=50),
        ),
        migrations.AddField(
            model_name='address',
            name='billing_address_phone',
            field=models.CharField(default='N.A', max_length=10),
        ),
    ]
